services:
  #  postgres:
  #    image: postgres:15.1
  #    ports:
  #      - ${DATABASE_PORT}:5432
  #    volumes:
  #      - ./.data/db:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_USER: ${DATABASE_USERNAME}
  #      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  #      POSTGRES_DB: ${DATABASE_NAME}
  #  redis:
  #    image: redis:7-alpine
  #    ports:
  #      - 6379:6379

  frontend:
    build:
      context: .
#    image: blackskin18/geni-cms-fe:latest
    env_file:
      - .env.production
    ports:
      - ${APP_PORT}:8000
#
